const formatLabel = (key) =>
  String(key)
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

const ACTION_TEXT = {
  confirm_diagnosis:
    "The AI recommends confirming this diagnosis based on the imaging findings and confidence level.",
  refer_specialist:
    "The AI recommends referral to an appropriate specialist for further clinical evaluation.",
  request_further_imaging:
    "The AI recommends additional imaging studies before a final clinical decision is made.",
};

const SEVERITY_TEXT = {
  normal: "Findings are within normal limits for the analyzed regions.",
  borderline: "Borderline findings were detected. Clinical correlation is advised.",
  pathology: "Pathological findings were detected. Prompt clinical review is recommended.",
};

const buildNarrative = (report) => {
  const p = report.prediction;
  const conf = Math.round(p.confidence * 1000) / 10;
  const primary = formatLabel(p.primary_diagnosis);
  const action =
    ACTION_TEXT[p.action] ||
    `Recommended action: ${formatLabel(p.action)}. ${p.action_rationale}`;

  const probabilityLines = Object.entries(p.predictions || {})
    .sort((a, b) => b[1] - a[1])
    .map(([disease, prob]) => `- ${formatLabel(disease)}: ${(prob * 100).toFixed(1)}%`)
    .join("\n");

  return [
    "CLINICAL DECISION SUPPORT REPORT",
    "================================",
    "",
    `Patient Study File: ${report.file_name || "Medical image"}`,
    `Case Reference: ${report.case_id}`,
    `Report Date: ${new Date(report.created_at).toLocaleString("en-US")}`,
    `AI Model Version: ${p.model_version}`,
    "",
    "PRIMARY FINDING",
    "---------------",
    `The artificial intelligence system identified "${primary}" as the most likely diagnosis`,
    `with a confidence score of ${conf}%.`,
    "",
    SEVERITY_TEXT[p.severity] || `Severity classification: ${p.severity}.`,
    "",
    p.low_confidence_flag
      ? "IMPORTANT: This result is flagged as LOW CONFIDENCE. A senior clinician should review this case before any clinical action."
      : "Confidence is within acceptable clinical support range, subject to physician verification.",
    "",
    "DIFFERENTIAL PROBABILITIES",
    "-------------------------",
    probabilityLines || "No probability breakdown available.",
    "",
    "CLINICAL RECOMMENDATION",
    "-----------------------",
    action,
    "",
    `Rationale: ${p.action_rationale}`,
    "",
    "EXPLAINABILITY",
    "--------------",
    p.gradcam_url
      ? "A Grad-CAM heatmap was generated to highlight regions that influenced this prediction. Review the heatmap alongside the source image."
      : "Grad-CAM heatmap was not available for this study.",
    "",
    "DISCLAIMER",
    "----------",
    "This report is generated by an AI clinical decision support system for assistance only.",
    "It does not replace professional medical judgment. All diagnoses and treatment",
    "decisions must be made by a licensed healthcare provider.",
  ].join("\n");
};

const buildHtml = (report) => {
  const p = report.prediction;
  const narrative = buildNarrative(report);
  const conf = Math.round(p.confidence * 1000) / 10;
  const primary = formatLabel(p.primary_diagnosis);

  const probRows = Object.entries(p.predictions || {})
    .sort((a, b) => b[1] - a[1])
    .map(
      ([disease, prob]) =>
        `<tr><td>${formatLabel(disease)}</td><td>${(prob * 100).toFixed(1)}%</td></tr>`
    )
    .join("");

  const narrativeHtml = narrative
    .split("\n")
    .map((line) => `<p style="margin:0 0 6px;font-size:14px;line-height:1.55;color:#334155">${line || "&nbsp;"}</p>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Clinical Report — ${report.case_id}</title>
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 800px; margin: 40px auto; padding: 24px; color: #1a2744; }
    h1 { font-family: Arial, sans-serif; color: #1a2744; border-bottom: 3px solid #3b6fd4; padding-bottom: 12px; }
    h2 { font-family: Arial, sans-serif; color: #3b6fd4; margin-top: 28px; font-size: 16px; }
    .meta { background: #f5f7fb; padding: 16px; border-radius: 8px; margin: 16px 0; font-size: 14px; }
    .highlight { background: #eef3fc; border-left: 4px solid #3b6fd4; padding: 16px; margin: 16px 0; }
    .warning { background: #fef3e8; border-left: 4px solid #f4a261; padding: 12px; margin: 16px 0; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-size: 14px; }
    th { background: #f5f7fb; }
    .disclaimer { font-size: 12px; color: #64748b; margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 16px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Clinical Decision Support Report</h1>
  <p style="color:#64748b;font-size:13px">Symptoms AI — Generated ${new Date().toLocaleString("en-US")}</p>

  <div class="meta">
    <strong>Case ID:</strong> ${report.case_id}<br/>
    <strong>File:</strong> ${report.file_name || "Medical image"}<br/>
    <strong>Study Date:</strong> ${new Date(report.created_at).toLocaleString("en-US")}<br/>
    <strong>Model Version:</strong> ${p.model_version}
  </div>

  <h2>Primary Diagnosis</h2>
  <div class="highlight">
    <p style="font-size:22px;font-weight:bold;margin:0 0 8px">${primary}</p>
    <p style="margin:0;font-size:16px">Confidence: <strong>${conf}%</strong> &nbsp;|&nbsp; Severity: <strong>${formatLabel(p.severity)}</strong></p>
  </div>

  ${p.low_confidence_flag ? '<div class="warning"><strong>Low Confidence Alert:</strong> This case requires senior clinician review before clinical action.</div>' : ""}

  <h2>Clinical Summary</h2>
  <div>${narrativeHtml}</div>

  <h2>Probability Breakdown</h2>
  <table><thead><tr><th>Condition</th><th>Probability</th></tr></thead><tbody>${probRows}</tbody></table>

  <h2>Recommended Action</h2>
  <p style="font-size:15px"><strong>${formatLabel(p.action)}</strong> — ${p.action_rationale}</p>

  <div class="disclaimer">
    This document is for clinical decision support only. Final diagnosis and treatment decisions rest with the attending physician.
  </div>
</body>
</html>`;
};

module.exports = { buildNarrative, buildHtml };
